import type { SpendingAnalysis } from "@/lib/analysis/types";

// Synthetic fixture based on the observed live analysis shape, with merchant names,
// amounts, and contextual details scrubbed for safe local development.
export const sampleSpendingAnalysisFixture: SpendingAnalysis = {
  accountCount: 4,
  baseline: {
    currency: "EUR",
    discretionaryMonthlySpend: 2448,
    raiseTarget: 245,
    targetPercentage: 0.1,
  },
  currencySummary: {
    otherCurrencies: ["GBP"],
    primaryCurrency: "EUR",
  },
  debugCounts: {
    behaviouralTransactions: 246,
    excludedOneOffTransactions: 6,
    fixedCostTransactions: 14,
    totalTransactions: 592,
    uncertainTransactions: 84,
    wealthFlowTransactions: 252,
  },
  fixedCostContext: [
    {
      categoryKey: "utilities",
      label: "Utilities",
      merchantExamples: ["Energy provider", "Mobile carrier", "Home broadband"],
      monthlySpend: 214,
    },
    {
      categoryKey: "housing",
      label: "Housing",
      merchantExamples: ["Rent transfer"],
      monthlySpend: 1180,
    },
    {
      categoryKey: "banking_fees",
      label: "Banking fees",
      merchantExamples: ["Premium account plan"],
      monthlySpend: 18,
    },
  ],
  generatedAt: "2026-04-17T12:00:00.000Z",
  habitMerchants: [
    {
      averageSpend: 29,
      categoryKey: "delivery",
      confidence: "high",
      count: 8,
      label: "Meal courier",
      monthlySpend: 77,
      pattern: "habit",
    },
    {
      averageSpend: 16,
      categoryKey: "coffee_snacks",
      confidence: "high",
      count: 10,
      label: "Coffee kiosk",
      monthlySpend: 53,
      pattern: "habit",
    },
    {
      averageSpend: 24,
      categoryKey: "grocery",
      confidence: "high",
      count: 12,
      label: "Neighbourhood grocery",
      monthlySpend: 96,
      pattern: "habit",
    },
    {
      averageSpend: 22,
      categoryKey: "transport",
      confidence: "high",
      count: 6,
      label: "Ride share app",
      monthlySpend: 44,
      pattern: "habit",
    },
    {
      averageSpend: 41,
      categoryKey: "shopping_general",
      confidence: "medium",
      count: 4,
      label: "Home goods shop",
      monthlySpend: 55,
      pattern: "habit",
    },
    {
      averageSpend: 35,
      categoryKey: "eating_out",
      confidence: "high",
      count: 5,
      label: "Weekend dinner spot",
      monthlySpend: 58,
      pattern: "habit",
    },
  ],
  subscriptions: [
    {
      confidence: "high",
      count: 3,
      label: "Streaming bundle",
      monthlySpend: 34,
      sampleAmount: 17,
    },
    {
      confidence: "high",
      count: 2,
      label: "Cloud storage plan",
      monthlySpend: 18,
      sampleAmount: 9,
    },
    {
      confidence: "medium",
      count: 2,
      label: "AI assistant plan",
      monthlySpend: 40,
      sampleAmount: 20,
    },
    {
      confidence: "high",
      count: 2,
      label: "Fitness membership",
      monthlySpend: 52,
      sampleAmount: 26,
    },
    {
      confidence: "medium",
      count: 2,
      label: "Language learning app",
      monthlySpend: 14,
      sampleAmount: 7,
    },
  ],
  topLevers: [
    {
      categoryKey: "subscriptions",
      confidence: "high",
      controllabilityScore: 0.68,
      estimatedHalfCutImpact: 122,
      label: "Subscriptions",
      merchantExamples: ["Streaming bundle", "AI assistant plan", "Cloud storage plan"],
      monthlySpend: 244,
      targetCoverage: 0.498,
    },
    {
      categoryKey: "delivery",
      confidence: "high",
      controllabilityScore: 0.95,
      estimatedHalfCutImpact: 84,
      label: "Delivery",
      merchantExamples: ["Meal courier", "Late-night takeaway", "Lunch delivery"],
      monthlySpend: 168,
      targetCoverage: 0.343,
    },
    {
      categoryKey: "eating_out",
      confidence: "high",
      controllabilityScore: 0.75,
      estimatedHalfCutImpact: 73,
      label: "Eating out",
      merchantExamples: ["Neighbourhood bistro", "Weekend dinner spot", "Lunch counter"],
      monthlySpend: 146,
      targetCoverage: 0.298,
    },
  ],
  uncertainSpend: [
    {
      label: "Digital marketplace",
      merchantFamily: "digital_marketplace",
      monthlySpend: 94,
      reason: "Ambiguous digital merchant kept broad on purpose.",
      transactionCount: 4,
    },
    {
      label: "Department store",
      monthlySpend: 81,
      reason: "No confident merchant rule matched.",
      transactionCount: 2,
    },
    {
      label: "Travel reseller",
      monthlySpend: 66,
      reason: "No confident merchant rule matched.",
      transactionCount: 1,
    },
    {
      label: "Payment platform seller",
      merchantFamily: "payment_platform",
      monthlySpend: 38,
      reason: "Ambiguous merchant family kept broad on purpose.",
      transactionCount: 1,
    },
  ],
};
